[env.production]
name = "drodolcom"
workers_dev = true
compatibility_date = "2024-11-25"

# Environment variables can be added here if needed
# [vars]
# EXAMPLE_VAR = "value"

[site]
bucket = "./dist"
