name = "drodolcom"

# Cloudflare Pages configuration
# Pages projects are managed via the dashboard or wrangler pages commands

# For local development and manual deployments
compatibility_date = "2024-11-25"
pages_build_output_dir = "dist"
