name = "drodolcom"
main = "./dist/_worker.js"
compatibility_date = "2024-11-25"
compatibility_flags = ["nodejs_compat"]

# Environment variables can be added here if needed
[vars]
BLUESKY_USERNAME = "drodol.com"

[[routes]]
pattern = "drodol.com/*"
zone_name = "drodol.com"

[site]
bucket = "./dist"
