[env.production]
name = "drodolcom"
workers_dev = true
compatibility_date = "2024-11-25"

[vars]
BLUESKY_USERNAME = "drodol.com"

# Use [secrets] for sensitive values that should be set via wrangler
# [secrets]
# BLUESKY_APP_PASSWORD

[site]
bucket = "./dist"
